version: '3'

services:
   # Data Source - MySQL Database
   mysql:
     image: "mysql:8.0"
     ports:
       - "3306:3306"
     environment:
       - MYSQL_DATABASE=gravity
       - MYSQL_USER=mysql
       - MYSQL_PASSWORD=1qaz@WSX
       - MYSQL_ROOT_PASSWORD=1qaz@WSXROOT
     volumes:
       - ${PWD}/createTable.sql:/docker-entrypoint-initdb.d/init.sql

   # Destination - Postgres Database
   postgres:
     image: "postgres:9"
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=gravity
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=1qaz@WSX
     volumes:
       - ${PWD}/createTable.sql:/docker-entrypoint-initdb.d/init.sql

   # Gravity Core Components
   internal-nats-server:
     image: "nats:2.2.6"
     restart: always
     expose:
     - "4222"
     ports:
       - "4222:4222"

   gravity-controller:
     image: "brobridgehub/gravity-controller:v2.0.0"
     hostname: gravity-controller
     restart: always
     environment:
     - GRAVITY_CONTROLLER_GRAVITY_HOST=internal-nats-server
     - GRAVITY_CONTROLLER_GRAVITY_PORT=4222
     depends_on:
     - "internal-nats-server"

   # Data Mapping Rules
   gravity-synchronizer:
     image: "brobridgehub/gravity-synchronizer:v4.0.0"
     restart: always
     hostname: gravity-synchronizer
     environment:
       GRAVITY_SYNCHRONIZER_GRAVITY_HOST: internal-nats-server
       GRAVITY_SYNCHRONIZER_GRAVITY_PORT: 4222
       GRAVITY_SYNCHRONIZER_RULES_SETTINGS: |
         {
          "rules": [
            {
              "event": "accountInitialized",
              "collection": "accountData",
              "method": "insert",
              "primaryKey": "id",
              "mapping": [
                {
                  "source": "id",
                  "target": "id"
                },
                {
                  "source": "name",
                  "target": "name"
                },
                {
                  "source": "email",
                  "target": "email"
                }
              ]
            },
            {
              "event": "accountCreated",
              "collection": "accountData",
              "method": "insert",
              "primaryKey": "id",
              "mapping": [
                {
                  "source": "id",
                  "target": "id"
                },
                {
                  "source": "name",
                  "target": "name"
                },
                {
                  "source": "email",
                  "target": "email"
                }
              ]
            },
            {
              "event": "accountUpdated",
              "collection": "accountData",
              "method": "update",
              "primaryKey": "id",
              "mapping": [
                {
                  "source": "id",
                  "target": "id"
                },
                {
                  "source": "name",
                  "target": "name"
                },
                {
                  "source": "email",
                  "target": "email"
                }
              ]
            },
            {
              "event": "accountDeleted",
              "collection": "accountData",
              "method": "delete",
              "primaryKey": "id",
              "mapping": [
                {
                  "source": "id",
                  "target": "id"
                }
              ]
            }
          ]
         }
     depends_on:
     - "gravity-controller"
     - "internal-nats-server"

   # Destination Settings
   gravity-transmitter-postgres:
     image: "brobridgehub/gravity-transmitter-postgres:v3.0.0"
     hostname: gravity-transmitter-postgres
     restart: always
     environment:
       GRAVITY_TRANSMITTER_POSTGRES_GRAVITY_HOST: 172.17.0.1:4222
       GRAVITY_TRANSMITTER_POSTGRES_DATABASE_HOST: 172.17.0.1
       GRAVITY_TRANSMITTER_POSTGRES_DATABASE_PORT: 5432
       GRAVITY_TRANSMITTER_POSTGRES_DATABASE_USERNAME: postgres
       GRAVITY_TRANSMITTER_POSTGRES_DATABASE_PASSWORD: 1qaz@WSX
       GRAVITY_TRANSMITTER_POSTGRES_DATABASE_DBNAME: gravity
       GRAVITY_TRANSMITTER_POSTGRES_SUBSCRIPTION_SETTINGS: |  
        {                
                "subscriptions": {
                        "accountData": [
                                "accounts"
                        ]
                }        
        }
     depends_on:
     - "gravity-synchronizer"
     - "postgres"

   # Data Source Settings
   gravity-adapter-mysql:
     image: "brobridgehub/gravity-adapter-mysql:v2.0.0"
     restart: always
     hostname: gravity-adapter-mysql
     environment:
       GRAVITY_ADAPTER_MYSQL_GRAVITY_HOST: 172.17.0.1
       GRAVITY_ADAPTER_MYSQL_GRAVITY_PORT: 4222
       GRAVITY_ADAPTER_MYSQL_SOURCE_SETTINGS: |
         {
              "sources": {
                      "mysql_example": {
                              "disabled": false,
                              "host": "172.17.0.1",
                              "port": 3306,
                              "username": "root",
                              "password": "1qaz@WSXROOT",
                              "dbname": "gravity",
                              "initialLoad": true,
                              "tables": {
                                      "users":{
                                              "events": {
                                                      "snapshot": "accountInitialized",
                                                      "create": "accountCreated",
                                                      "update": "accountUpdated",
                                                      "delete": "accountDeleted"
                                              }
                                      }
                              }
                      }
              }
         }
     depends_on:
     - "gravity-synchronizer"
     - "mysql"
